=== KateLaurynovich/JD2016-08-29/src/by/it/emelyanov/jd02_08/Hotel.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://jd02_08.emelyanov.it.by/xml/Hotels"
        xmlns:tns="http://jd02_08.emelyanov.it.by/xml/Hotels"
        elementFormDefault="qualified">

    <element name="Hotels">
        <complexType>
            <sequence>
                <element name="Hotel"
                         type="tns:Hotel"
                         maxOccurs="unbounded">

                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Hotel">
        <sequence>

            <element name="Clients">
                <complexType>
                    <sequence>
                        <element name="client" maxOccurs="unbounded" minOccurs="0">
                            <complexType>
                                <sequence>
                                    <element type="string" name="name"/>
                                    <element type="string" name="surname"/>
                                    <element type="string" name="middleName"/>
                                    <element type="string" name="email"/>
                                    <element type="string" name="passport"/>
                                    <element type="string" name="login"/>
                                    <element type="string" name="password"/>
                                </sequence>
                                <attribute type="byte" name="client_id" use="optional"/>
                            </complexType>
                        </element>
                    </sequence>
                </complexType>
            </element>

            <element name="Apartments">
                <complexType>
                    <sequence>
                        <element name="apartment" maxOccurs="unbounded" minOccurs="0">
                            <complexType>
                                <sequence>
                                    <element type="float" name="floor"/>
                                    <element type="float" name="room_number"/>
                                    <element type="float" name="places"/>
                                    <element type="string" name="category"/>
                                    <element type="float" name="cost"/>
                                    <element type="string" name="status"/>
                                </sequence>
                                <attribute type="byte" name="apartment_id" use="optional"/>
                            </complexType>
                        </element>
                    </sequence>
                </complexType>
            </element>

            <element name="Orders">
                <complexType>
                    <sequence>
                        <element name="order" maxOccurs="unbounded" minOccurs="0">
                            <complexType>
                                <sequence>
                                    <element type="float" name="user_id"/>
                                    <element type="float" name="apartment_id"/>
                                    <element type="string" name="arrive_date"/>
                                    <element type="string" name="return_date"/>
                                    <element type="float" name="bill"/>
                                </sequence>
                                <attribute type="byte" name="order_id" use="optional"/>
                            </complexType>
                        </element>
                    </sequence>
                </complexType>
            </element>

        </sequence>
        <attribute type="string" name="name"/>
    </complexType>

</schema>

=== KateLaurynovich/JD2016-08-29/src/by/it/emelyanov/jd02_08/Hotel+XSD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Hotels xmlns="http://jd02_08.emelyanov.it.by/xml/Hotels"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://jd02_08.emelyanov.it.by/xml/Hotels Hotel.xsd">
    <Hotel name="Minsk Hotel">
        <Clients>
            <client client_id="1">
                <name>
                    Сергей
                </name>
                <surname>
                    Рыбкин
                </surname>
                <middleName>
                    Владимирович
                </middleName>
                <email>
                    serp@gmail.com
                </email>
                <passport>
                    KH3125325
                </passport>
                <login>
                    serg
                </login>
                <password>
                    123qwe
                </password>
            </client>
            <client client_id="2">
                <name>
                    Павел
                </name>
                <surname>
                    Свободин
                </surname>
                <middleName>
                    Владимирович
                </middleName>
                <email>
                    pavel@mail.ru
                </email>
                <passport>
                    KH1225253
                </passport>
                <login>
                    pashka
                </login>
                <password>
                    1qa2ws3ed
                </password>
            </client>
        </Clients>
        <Apartments>
            <apartment apartment_id="1">
                <floor>
                    12
                </floor>
                <room_number>
                    65
                </room_number>
                <places>
                    2
                </places>
                <category>
                    basic
                </category>
                <cost>
                    45
                </cost>
                <status>
                    true or false
                </status>
            </apartment>
            <apartment apartment_id="2">
                <floor>
                    6
                </floor>
                <room_number>
                    34
                </room_number>
                <places>
                    1
                </places>
                <category>
                    luxury
                </category>
                <cost>
                    350
                </cost>
                <status>
                    true or false
                </status>
            </apartment>
        </Apartments>
        <Orders>
            <order order_id="1">
                <user_id>
                    1
                </user_id>
                <apartment_id>
                    1
                </apartment_id>
                <arrive_date>
                    19.10.2016
                </arrive_date>
                <return_date>
                    20.10.2016
                </return_date>
                <bill>
                    45
                </bill>
            </order>
            <order order_id="2">
                <user_id>
                    2
                </user_id>
                <apartment_id>
                    2
                </apartment_id>
                <arrive_date>
                    16.10.2016
                </arrive_date>
                <return_date>
                    20.10.2016
                </return_date>
                <bill>
                    350
                </bill>
            </order>
        </Orders>
    </Hotel>
</Hotels>
