<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE Persons [
        <!ELEMENT Persons (Person)+>
        <!ELEMENT Person (Email, Nickname, Password, Ads)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Nickname (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Ads (Ad)>
        <!ELEMENT Ad (Description, Address, Floor, Floors, Square)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Address (#PCDATA)>
        <!ELEMENT Floor (#PCDATA)>
        <!ELEMENT Floors (#PCDATA)>
        <!ELEMENT Square (#PCDATA)>
        ]>
<Persons>
    <Person>
        <Email>
            tsydzik.eugene@gmail.com
        </Email>
        <Nickname>Tsyd</Nickname>
        <Password>1111</Password>
        <Ads>
            <Ad>
                <Description>
                    Хорошая квартира
                </Description>
                <Address>
                    Тимирязева 65
                </Address>
                <Floor>3</Floor>
                <Floors>5</Floors>
                <Square>49.0</Square>
            </Ad>
        </Ads>
    </Person>
    <Person>
        <Email>
            tsyd@tut.by
        </Email>
        <Nickname>Dmitry</Nickname>
        <Password>2222</Password>
        <Ads>
            <Ad>
                <Description>
                    Очень хорошая квартира
                </Description>
                <Address>
                    Сердича 11
                </Address>
                <Floor>2</Floor>
                <Floors>9</Floors>
                <Square>50</Square>
            </Ad>
        </Ads>
    </Person>
</Persons>