=== KateLaurynovich/JD2016-08-29/src/by/it/rudzko/jd03_02/POJO/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema   xmlns="http://www.w3.org/2001/XMLSchema"
          targetNamespace="http://jd03_02.POJO.rudzko.it.by/"
          xmlns:ok="http://jd03_02.POJO.rudzko.it.by/"
          elementFormDefault="qualified">

    <element name="myDataBase" type="ok:myDataBase"/>

    <complexType name="myDataBase">
        <all>
            <element name="Roles" type="ok:Roles"/>
            <element name="Users"  type="ok:Users"/>
            <element name="Readership" type="ok:Readership"/>
            <element name="Periodicals" type="ok:Periodicals"/>
            <element name="Subscription" type="ok:Subscription"/>
        </all>
    </complexType>

    <complexType name="Roles">
        <sequence>
            <element name="Role"
                     type="ok:Role"
                     minOccurs="1"
                     maxOccurs="2"/>
        </sequence>
    </complexType>

    <complexType name="Role">
        <sequence>
            <element name="ID" type="int"/>
            <element name="Participant" type="string"/>
        </sequence>
    </complexType>

    <complexType name="Users">
        <sequence>
            <element name="User"
                     type="ok:User"
                     minOccurs="1"
                     maxOccurs="unbounded"
            />
        </sequence>
    </complexType>

    <complexType name="User">
        <sequence>
            <element name="ID" type="int"/>
            <element name="Name" type="string"/>
            <element name="Role" type="ok:Role"/>
            <element name="BirthYear" type="ok:year"/>
            <element name="Sex" type="string"/>
        </sequence>
    </complexType>

    <complexType name="Readership">
        <sequence>
            <element name="Audience"
                     type="ok:Audience"
                     minOccurs="1"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Audience">
        <sequence>
            <element name="ID" type="int"/>
            <element name="Group" type="string"/>
        </sequence>
    </complexType>

    <complexType name="Periodicals">
        <sequence>
            <element name="Periodical"
                     type="ok:Periodical"
                     minOccurs="1"
                     maxOccurs="unbounded"
            />
        </sequence>
    </complexType>

    <complexType name="Periodical">
        <sequence>
            <element name="ID" type="int"/>
            <element name="Title" type="string"/>
            <element name="SubIndex" type="ok:index"/>
            <element name="Audience" type="ok:Audience"/>
            <element name="AddedBy" type="ok:User"/>
        </sequence>
    </complexType>

    <complexType name="Subscription">
        <sequence>
            <element name="Subscr"
                     type="ok:Subscr"
                     minOccurs="1"
                     maxOccurs="unbounded"
            />
        </sequence>
    </complexType>

    <complexType name="Subscr">
        <sequence>
            <element name="ID" type="int"/>
            <element name="Periodical" type="ok:Periodical"/>
            <element name="Subscriber" type="ok:User"/>
        </sequence>
    </complexType>

    <simpleType name="year">
        <restriction base="int">
            <minInclusive value="1900"/>
            <maxInclusive value="2013"/>
        </restriction>
    </simpleType>

    <simpleType name="index">
        <restriction base="int">
            <minInclusive value="10000"/>
            <maxInclusive value="100000"/>
        </restriction>
    </simpleType>

</schema>

=== KateLaurynovich/JD2016-08-29/src/by/it/rudzko/jd03_02/POJO/newDataBase.xml
<?xml version="1.0" encoding="UTF-8"?>
<myDataBase xmlns="http://jd03_02.POJO.rudzko.it.by/"
            xmlns:ok="http://www.w3.org/2001/XMLSchema-instance"
            ok:schemaLocation="http://jd03_02.POJO.rudzko.it.by/ schema.xsd">
    <Roles>
        <Role>
            <ID>1</ID>
            <Participant>Администратор</Participant>
        </Role>
        <Role>
            <ID>2</ID>
            <Participant>Подписчик</Participant>
        </Role>
    </Roles>
    <Users>
        <User>
            <ID>1</ID>
            <Name>Иван</Name>
            <Role>
                <ID>1</ID>
                <Participant>Администратор</Participant>
            </Role>
            <BirthYear>1990</BirthYear>
             <Sex>M</Sex>
        </User>
        <User>
            <ID>2</ID>
            <Name>Марья</Name>
            <Role>
                <ID>2</ID>
                <Participant>Подписчик</Participant>
            </Role>
            <BirthYear>1995</BirthYear>
            <Sex>F</Sex>
        </User>
        <User>
            <ID>3</ID>
            <Name>Руслан</Name>
            <Role>
                <ID>2</ID>
                <Participant>Подписчик</Participant>
            </Role>
            <BirthYear>1985</BirthYear>
            <Sex>M</Sex>
        </User>
        <User>
            <ID>4</ID>
            <Name>Людмила</Name>
            <Role>
                <ID>2</ID>
                <Participant>Подписчик</Participant>
            </Role>
            <BirthYear>1990</BirthYear>
            <Sex>F</Sex>
        </User>
    </Users>
    <Readership>
        <Audience>
            <ID>1</ID>
            <Group>Adults</Group>
        </Audience>
        <Audience>
            <ID>2</ID>
            <Group>Men</Group>
        </Audience>
        <Audience>
            <ID>3</ID>
            <Group>Women</Group>
        </Audience>
        <Audience>
            <ID>4</ID>
            <Group>Teens</Group>
        </Audience>
        <Audience>
            <ID>5</ID>
            <Group>Children</Group>
        </Audience>
    </Readership>
    <Periodicals>
        <Periodical>
            <ID>1</ID>
            <Title>Дзеяслоў</Title>
            <SubIndex>74813</SubIndex>
            <Audience>
                <ID>1</ID>
                <Group>Adults</Group>
            </Audience>
            <AddedBy>
                <ID>1</ID>
                <Name>Иван</Name>
                <Role>
                    <ID>1</ID>
                    <Participant>Администратор</Participant>
                </Role>
                <BirthYear>1990</BirthYear>
                <Sex>M</Sex>
            </AddedBy>
        </Periodical>
        <Periodical>
            <ID>2</ID>
            <Title>Маладосць</Title>
            <SubIndex>74957</SubIndex>
            <Audience>
                <ID>4</ID>
                <Group>Teens</Group>
            </Audience>
            <AddedBy>
                <ID>1</ID>
                <Name>Иван</Name>
                <Role>
                    <ID>1</ID>
                    <Participant>Администратор</Participant>
                </Role>
                <BirthYear>1990</BirthYear>
                <Sex>M</Sex>
            </AddedBy>
        </Periodical>
        <Periodical>
            <ID>3</ID>
            <Title>Алеся</Title>
            <SubIndex>74995</SubIndex>
            <Audience>
                <ID>3</ID>
                <Group>Women</Group>
            </Audience>
            <AddedBy>
                <ID>1</ID>
                <Name>Иван</Name>
                <Role>
                    <ID>1</ID>
                    <Participant>Администратор</Participant>
                </Role>
                <BirthYear>1990</BirthYear>
                <Sex>M</Sex>
            </AddedBy>
        </Periodical>
        <Periodical>
            <ID>4</ID>
            <Title>Планета</Title>
            <SubIndex>75036</SubIndex>
            <Audience>
                <ID>1</ID>
                <Group>Adults</Group>
            </Audience>
            <AddedBy>
                <ID>1</ID>
                <Name>Иван</Name>
                <Role>
                    <ID>1</ID>
                    <Participant>Администратор</Participant>
                </Role>
                <BirthYear>1990</BirthYear>
                <Sex>M</Sex>
            </AddedBy>
        </Periodical>
        <Periodical>
            <ID>5</ID>
            <Title>Женский Журнал</Title>
            <SubIndex>74810</SubIndex>
            <Audience>
                <ID>3</ID>
                <Group>Women</Group>
            </Audience>
            <AddedBy>
                <ID>1</ID>
                <Name>Иван</Name>
                <Role>
                    <ID>1</ID>
                    <Participant>Администратор</Participant>
                </Role>
                <BirthYear>1990</BirthYear>
                <Sex>M</Sex>
            </AddedBy>
        </Periodical>
        <Periodical>
            <ID>6</ID>
            <Title>Наша Ніва</Title>
            <SubIndex>63125</SubIndex>
            <Audience>
                <ID>1</ID>
                <Group>Adults</Group>
            </Audience>
            <AddedBy>
                <ID>1</ID>
                <Name>Иван</Name>
                <Role>
                    <ID>1</ID>
                    <Participant>Администратор</Participant>
                </Role>
                <BirthYear>1990</BirthYear>
                <Sex>M</Sex>
            </AddedBy>
        </Periodical>
        <Periodical>
            <ID>7</ID>
            <Title>Культура</Title>
            <SubIndex>63875</SubIndex>
            <Audience>
                <ID>1</ID>
                <Group>Adults</Group>
            </Audience>
            <AddedBy>
                <ID>1</ID>
                <Name>Иван</Name>
                <Role>
                    <ID>1</ID>
                    <Participant>Администратор</Participant>
                </Role>
                <BirthYear>1990</BirthYear>
                <Sex>M</Sex>
            </AddedBy>
        </Periodical>
        <Periodical>
            <ID>8</ID>
            <Title>Минский курьер</Title>
            <SubIndex>63395</SubIndex>
            <Audience>
                <ID>1</ID>
                <Group>Adults</Group>
            </Audience>
            <AddedBy>
                <ID>1</ID>
                <Name>Иван</Name>
                <Role>
                    <ID>1</ID>
                    <Participant>Администратор</Participant>
                </Role>
                <BirthYear>1990</BirthYear>
                <Sex>M</Sex>
            </AddedBy>
        </Periodical>
        <Periodical>
            <ID>9</ID>
            <Title>Беларусь Сегодня</Title>
            <SubIndex>63889</SubIndex>
            <Audience><ID>1</ID>
                <Group>Adults</Group></Audience>
            <AddedBy>
                <ID>1</ID>
                <Name>Иван</Name>
                <Role>
                    <ID>1</ID>
                    <Participant>Администратор</Participant>
                </Role>
                <BirthYear>1990</BirthYear>
                <Sex>M</Sex>
            </AddedBy>
        </Periodical>
        <Periodical>
            <ID>10</ID>
            <Title>Прессбол</Title>
            <SubIndex>63115</SubIndex>
            <Audience>
                <ID>2</ID>
                <Group>Men</Group>
            </Audience>
            <AddedBy>
                <ID>1</ID>
                <Name>Иван</Name>
                <Role>
                    <ID>1</ID>
                    <Participant>Администратор</Participant>
                </Role>
                <BirthYear>1990</BirthYear>
                <Sex>M</Sex>
            </AddedBy>
        </Periodical>
    </Periodicals>
    <Subscription>
        <Subscr>
            <ID>1</ID>
            <Periodical>
                <ID>8</ID>
                <Title>Минский курьер</Title>
                <SubIndex>63395</SubIndex>
                <Audience>
                    <ID>1</ID>
                    <Group>Adults</Group>
                </Audience>
                <AddedBy>
                    <ID>1</ID>
                    <Name>Иван</Name>
                    <Role>
                        <ID>1</ID>
                        <Participant>Администратор</Participant>
                    </Role>
                    <BirthYear>1990</BirthYear>
                    <Sex>M</Sex>
                </AddedBy>
            </Periodical>
            <Subscriber>
                <ID>3</ID>
                <Name>Руслан</Name>
                <Role>
                    <ID>2</ID>
                    <Participant>Подписчик</Participant>
                </Role>
                <BirthYear>1985</BirthYear>
                <Sex>M</Sex>
            </Subscriber>
        </Subscr>
        <Subscr>
            <ID>2</ID>
            <Periodical>
                <ID>10</ID>
                <Title>Прессбол</Title>
                <SubIndex>63115</SubIndex>
                <Audience>
                    <ID>2</ID>
                    <Group>Men</Group>
                </Audience>
                <AddedBy>
                    <ID>1</ID>
                    <Name>Иван</Name>
                    <Role>
                        <ID>1</ID>
                        <Participant>Администратор</Participant>
                    </Role>
                    <BirthYear>1990</BirthYear>
                    <Sex>M</Sex>
                </AddedBy>
            </Periodical>
            <Subscriber>
                <ID>4</ID>
                <Name>Людмила</Name>
                <Role>
                    <ID>2</ID>
                    <Participant>Подписчик</Participant>
                </Role>
                <BirthYear>1990</BirthYear>
                <Sex>F</Sex>
            </Subscriber>
        </Subscr>
        <Subscr>
            <ID>3</ID>
            <Periodical>
                <ID>4</ID>
