<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE Persons [<!ELEMENT Persons (Person)+>
        <!ELEMENT Person (Email, Nickname, Password, Ads)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Nickname (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Ads (Ad)+>
        <!ELEMENT Ad (Description, Adress, Floor, Floors, Square)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Adress (#PCDATA)>
        <!ELEMENT Floor (#PCDATA)>
        <!ELEMENT Floors (#PCDATA)>
        <!ELEMENT Square (#PCDATA)>
        ]>
<Persons>
    <Person>
        <Email>
            ivanov@mail.ru
        </Email>
        <Nickname>
            Ivan1988
        </Nickname>
        <Password>
            01011988
        </Password>
        <Ads>
            <Ad>
                <Description>
                    Очень хорошая квартира.
                </Description>
                <Adress>
                    ул. В. Хоружей д. 13 кв. 12
                </Adress>
                <Floor>
                    23
                </Floor>
                <Floors>
                    25
                </Floors>
                <Square>
                    79.0
                </Square>
            </Ad>
            <Ad>
                <Description>
                    Хорошая квартира.
                </Description>
                <Adress>
                    ул. В. Хоружей д. 11 кв. 12
                </Adress>
                <Floor>
                    3
                </Floor>
                <Floors>
                    5
                </Floors>
                <Square>
                    33.0
                </Square>
            </Ad>
        </Ads>
    </Person>
</Persons>