=== KateLaurynovich/JD2016-08-29/src/by/it/tsiamruk/jd02_07/paymentSystem.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="http://tsiamruk.it-academy.by/xml/paymentSystem"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="PaymentSystem">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Clients">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Client" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="Email"/>
                                        <xs:element type="xs:string" name="Login"/>
                                        <xs:element type="xs:string" name="Password"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Accounts">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Account" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:float" name="TotalAmount"/>
                                        <xs:element type="xs:string" name="Status"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Admin">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="Login"/>
                            <xs:element type="xs:string" name="Password"/>
                            <xs:element name="UnlockAccount">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:float" name="getId"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== KateLaurynovich/JD2016-08-29/src/by/it/tsiamruk/jd02_07/paymentSystem.xml
<?xml version="1.0" encoding="UTF-8" ?>
<PaymentSystem xmlns="http://tsiamruk.it-academy.by/xml/paymentSystem"
               xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
               xs:schemaLocation="http://tsiamruk.it-academy.by/xml/paymentSystem paymentSystem.xsd">
    <Clients>
        <Client>
            <Email>
                ivan@ivanov.com
            </Email>
            <Login>
                Ivan001
            </Login>
            <Password>
                qwerty123
            </Password>
        </Client>
        <Client>
            <Email>
                bogdan@bogdanov.com
            </Email>
            <Login>
                BogdigLoL
            </Login>
            <Password>
                qwerty0123
            </Password>
        </Client>
    </Clients>
    <Accounts>
        <Account>
            <TotalAmount>
                1000
            </TotalAmount>
            <Status>
                Unlocked
            </Status>
        </Account>
        <Account>
            <TotalAmount>
                2
            </TotalAmount>
            <Status>
                Blocked
            </Status>
        </Account>
    </Accounts>
    <Admin>
        <Login>
            root
        </Login>
        <Password>
            root
        </Password>
        <UnlockAccount>
            <getId>
                00000
            </getId>
        </UnlockAccount>
    </Admin>
</PaymentSystem>
