=== KateLaurynovich/JD2016-08-29/src/by/it/vashukevich/jd02_07/classwork/jd02_07/elective.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://vashukevich.it-academy.by/xml/Elective"
    xmlns:tns="http://vashukevich.it-academy.by/xml/Elective"
    elementFormDefault="qualified">
    <element name="Elective">
        <complexType>
            <sequence>
                <element name="Course"
                         type="tns:Course"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Course">
        <sequence>
            <element name="Title" type="string"/>
            <element name="Teachers" type="tns:Teachers"/>
            <element name="SumStudents" type="int"/>
            <element name="NumberOfHours" type="double"/>
            <element name="CourseStart" type="date"/>
        </sequence>
    </complexType>

    <complexType name="Teachers">
        <sequence>
            <element name="Teacher"
                     type="tns:Teacher"
                     minOccurs="1"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Teacher">
        <sequence>
            <element name="SurName" type="string"/>
            <element name="Name" type="string"/>
            <element name="Patronymic" type="string"/>
        </sequence>
    </complexType>
</schema>

=== KateLaurynovich/JD2016-08-29/src/by/it/vashukevich/jd02_07/classwork/jd02_07/elective+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Elective xmlns="http://vashukevich.it-academy.by/xml/Elective"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://vashukevich.it-academy.by/xml/Elective elective.xsd">
    <Course>
        <Title>Java Developer Course</Title>
        <Teachers>
            <Teacher>
                <SurName>Иванов</SurName>
                <Name>Аристарх</Name>
                <Patronymic>Алефтинович</Patronymic>
            </Teacher>

            <Teacher>
                <SurName>Сидоров</SurName>
                <Name>Людвиг</Name>
                <Patronymic>Аристархович</Patronymic>
            </Teacher>
        </Teachers>

        <SumStudents>15</SumStudents>
        <NumberOfHours>120.0</NumberOfHours>
        <CourseStart>2017-01-01</CourseStart>
    </Course>
    <Course>
        <Title>Автоматизированное тестирование</Title>
        <Teachers>
            <Teacher>
               <SurName>Петров</SurName>
               <Name>Петр</Name>
               <Patronymic>Петрович</Patronymic>
            </Teacher>
            <Teacher>
               <SurName>Алексеев</SurName>
               <Name>Алексей</Name>
               <Patronymic>Алексеевич</Patronymic>
            </Teacher>
        </Teachers>
        <SumStudents>20</SumStudents>
        <NumberOfHours>110.0</NumberOfHours>
        <CourseStart>2017-01-01</CourseStart>
    </Course>
</Elective>
