=== KateLaurynovich/JD2016-08-29/src/by/it/sukora/jd02_07/hospital.dtd
<?xml version="1.0" encoding="utf-8"?>
        <!ELEMENT Hospital (Patients)>
        <!ELEMENT Patients (Patient) +>
        <!ATTLIST Patient name CDATA #REQUIRED>
        <!ELEMENT Patient (FirstName,MedicalCard, LastName, Sex, DateOfBirth, Passport, IssuedBy, IssuedDate, Login, Password, Phone, Address)>
        <!ELEMENT FirstName (#PCDATA)>
        <!ELEMENT LastName (#PCDATA)>
        <!ELEMENT Sex (#PCDATA)>
        <!ELEMENT DateOfBirth (#PCDATA)>
        <!ELEMENT Passport (#PCDATA)>
        <!ELEMENT IssuedBy (#PCDATA)>
        <!ELEMENT IssuedDate (#PCDATA)>
        <!ELEMENT Login (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Phone (#PCDATA)>

        <!ELEMENT Address (Country, City, Street, Building, Flat)>
        <!ELEMENT Country (#PCDATA)>
        <!ELEMENT City (#PCDATA)>
        <!ELEMENT Street (#PCDATA)>
        <!ELEMENT Building (#PCDATA)>
        <!ELEMENT Flat (#PCDATA)>

        <!ELEMENT MedicalCard (Diagnosis)+>
        <!ELEMENT Diagnosis (Disease,Sibptomps,PeriodStart,PeriodEnd,Recipe)>
        <!ATTLIST Diagnosis id CDATA #REQUIRED>
        <!ELEMENT Disease (#PCDATA)>
        <!ELEMENT Sibptomps (#PCDATA)>
        <!ELEMENT PeriodStart (#PCDATA)>
        <!ELEMENT PeriodEnd (#PCDATA)>
        <!ELEMENT Recipe (#PCDATA)>

=== KateLaurynovich/JD2016-08-29/src/by/it/sukora/jd02_07/ hospital.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Hospital SYSTEM "hospital.dtd" >
<Hospital>
    <Patients>
        <Patient name="Stas Sukora">
            <FirstName>Stas</FirstName>
            <LastName>Sukora</LastName>
            <Sex>M</Sex>
            <DateOfBirth>1979-09-12</DateOfBirth>
            <Passport>BM1932121</Passport>
            <IssuedBy>Minsk ROVD</IssuedBy>
            <IssuedDate>2010-12-15</IssuedDate>
            <Login>stas14141</Login>
            <Password>password1</Password>
            <Phone>+375294586954</Phone>
            <Address>
                <Country>Belarus</Country>
                <City>Minsk</City>
                <Street>Lenina</Street>
                <Building>3</Building>
                <Flat>21</Flat>
            </Address>
            <MedicalCard>
                <Diagnosis id="1">
                    <Disease>Грипп</Disease>
                    <Sibptomps>Кашель, высокая температура, знобь, головная боль</Sibptomps>
                    <PeriodStart>11 Ноября</PeriodStart>
                    <PeriodEnd>28 Ноября</PeriodEnd>
                    <Recipe>Азлобин, формацевтив</Recipe>
                </Diagnosis>
                <Diagnosis id="2">
                    <Disease>Гайморит</Disease>
                    <Sibptomps>Сильная боль в областе носа, высокая температура, знобьь</Sibptomps>
                    <PeriodStart>3 Января</PeriodStart>
                    <PeriodEnd>12 Февраля</PeriodEnd>
                    <Recipe>АнтиГайморит</Recipe>
                </Diagnosis>
                <Diagnosis id="3">
                    <Disease>Ротовирусная инфекция</Disease>
                    <Sibptomps>Тошнота, понос, высокая температура, недуг</Sibptomps>
                    <PeriodStart>3 Марта</PeriodStart>
                    <PeriodEnd>8 Марта</PeriodEnd>
                    <Recipe>Стоп диар, против температура</Recipe>
                </Diagnosis>
                <Diagnosis id="4">
                    <Disease>Простуда</Disease>
                    <Sibptomps>Насморк, небольшая температура</Sibptomps>
                    <PeriodStart>10 Апреля</PeriodStart>
                    <PeriodEnd>17 Апреля</PeriodEnd>
                    <Recipe>NULL</Recipe>
                </Diagnosis>
                <Diagnosis id="5">
                    <Disease>Апендецит</Disease>
                    <Sibptomps>Сильная боль в животе</Sibptomps>
                    <PeriodStart>20 Декабря</PeriodStart>
                    <PeriodEnd>12 Января</PeriodEnd>
                    <Recipe>Постельный режим, операция, диета</Recipe>
                </Diagnosis>
            </MedicalCard>
        </Patient>

        <Patient name="Nikita Nicrogodov">
            <FirstName>Nicita</FirstName>
            <LastName>Nicrogodov</LastName>
            <Sex>M</Sex>
            <DateOfBirth>1987-02-13</DateOfBirth>
            <Passport>MP1933541</Passport>
            <IssuedBy>Minsk ROVD</IssuedBy>
            <IssuedDate>2012-12-15</IssuedDate>
            <Login>loveMasha</Login>
            <Password>password231</Password>
            <Phone>+375294586954</Phone>
            <Address>
                <Country>Belarus</Country>
                <City>Minsk</City>
                <Street>Odoevskogo</Street>
                <Building>3</Building>
                <Flat>223</Flat>
            </Address>
            <MedicalCard>
                <Diagnosis id="1">
                    <Disease>Грипп</Disease>
                    <Sibptomps>Кашель, высокая температура, знобь, головная боль</Sibptomps>
                    <PeriodStart>11 Ноября</PeriodStart>
                    <PeriodEnd>28 Ноября</PeriodEnd>
                    <Recipe>Азлобин, формацевтив</Recipe>
                </Diagnosis>
                <Diagnosis id="2">
                    <Disease>Гайморит</Disease>
                    <Sibptomps>Сильная боль в областе носа, высокая температура, знобьь</Sibptomps>
                    <PeriodStart>3 Января</PeriodStart>
                    <PeriodEnd>12 Февраля</PeriodEnd>
                    <Recipe>АнтиГайморит</Recipe>
                </Diagnosis>
                <Diagnosis id="3">
                    <Disease>Эболла</Disease>
                    <Sibptomps>Тошнота, понос, высокая температура, недуг, летальный исход</Sibptomps>
                    <PeriodStart>3 Марта</PeriodStart>
                    <PeriodEnd>5 Марта</PeriodEnd>
                    <Recipe>кладбище</Recipe>
                </Diagnosis>
                <Diagnosis id="4">
                    <Disease>Простуда</Disease>
                    <Sibptomps>Насморк, небольшая температура</Sibptomps>
                    <PeriodStart>10 Апреля</PeriodStart>
                    <PeriodEnd>17 Апреля</PeriodEnd>
                    <Recipe>NULL</Recipe>
                </Diagnosis>
                <Diagnosis id="5">
                    <Disease>Апендецит</Disease>
                    <Sibptomps>Сильная боль в животе</Sibptomps>
                    <PeriodStart>20 Декабря</PeriodStart>
                    <PeriodEnd>12 Января</PeriodEnd>
                    <Recipe>Постельный режим, операция, диета</Recipe>
                </Diagnosis>
            </MedicalCard>
        </Patient>
    </Patients>
</Hospital>
