<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Persons [
        <!ELEMENT Persons (Person)+>
        <!ELEMENT Person (Email,Nickname,Password,Ads) >
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Nickname (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Ads (Ad)+>
        <!ELEMENT Ad (Description, Address, Floor, Floors, Square)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Address (#PCDATA)>
        <!ELEMENT Floor (#PCDATA)>
        <!ELEMENT Floors (#PCDATA)>
        <!ELEMENT Square (#PCDATA)>
        ] >
<Persons>
    <Person>
        <Email>
            ivanov@mail.ru
        </Email>
        <Nickname>
            Ivan1988
        </Nickname>
        <Password>
            01011988
        </Password>
        <Ads>
            <Ad>
                <Description>
                    Хорошая квартира.
                </Description>
                <Address>
                    Хоружей 13-12
                </Address>
                <Floor>
                    3
                </Floor>
                <Floors>
                    5
                </Floors>
                <Square>
                    49,0
                </Square>
            </Ad>

            <Ad>
                <Description>
                    Очень хорошая квартира.
                </Description>
                <Address>
                    Хоружей 13-12
                </Address>
                <Floor>
                    23
                </Floor>
                <Floors>
                    25
                </Floors>
                <Square>
                    79,0
                </Square>
            </Ad>

        </Ads>
    </Person>
</Persons>