=== KateLaurynovich/JD2016-08-29/src/by/it/senchenko/jd02_07/ad.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://akhmelev.it-academy.by/xml/Persons"
        xmlns:tns="http://akhmelev.it-academy.by/xml/Persons"
        elementFormDefault="qualified">
    <element name="Persons">
       <complexType>
           <sequence>
               <element name="Person"
                        type="tns:Person"
                        maxOccurs="unbounded">

               </element>
           </sequence>
       </complexType>
    </element>

    <complexType name="Person">
        <sequence>
            <element name="Email" type="string" />
            <element name="Nickname" type="string" />
            <element name="Password" type="string" />
            <element name="Ads" type="tns:Ads" />
        </sequence>
    </complexType>

    <complexType name="Ads">
        <sequence>
            <element name="Ad" type="tns:Ad"
                     minOccurs="1"
                     maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="Ad">
        <all>
            <element name="Description" type="string"/>
            <element name="Address" type="string"/>
            <element name="Floor" type="positiveInteger"/>
            <element name="Floors" type="positiveInteger"/>
            <element name="Square" type="double"/>
        </all>
    </complexType>

</schema>

=== KateLaurynovich/JD2016-08-29/src/by/it/senchenko/jd02_07/ad+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Persons xmlns="http://akhmelev.it-academy.by/xml/Persons"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://akhmelev.it-academy.by/xml/Persons ad.xsd"
>
    <Person>
        <Email>
            ivanov@mail.ru
        </Email>
        <Nickname>
            Ivan1988
        </Nickname>
        <Password>
            01011988
        </Password>
        <Ads>
            <Ad>
                <Description>
                    Хорошая квартира.
                </Description>
                <Address>
                    Хоружей 13-12
                </Address>
                <Floor>
                    3
                </Floor>
                <Floors>
                    5
                </Floors>
                <Square>
                    49.0
                </Square>
            </Ad>

            <Ad>
                <Description>
                    Очень хорошая квартира.
                </Description>
                <Address>
                    Хоружей 13-12
                </Address>
                <Floor>
                    23
                </Floor>
                <Floors>
                    25
                </Floors>
                <Square>
                    79.0
                </Square>
            </Ad>

        </Ads>
    </Person>
</Persons>

=== KateLaurynovich/JD2016-08-29/src/by/it/vashukevich/jd02_07/classwork/ad+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Persons xmlns="http://vashukevich.it-academy.by/xml/Persons"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://vashukevich.it-academy.by/xml/Persons ad.xsd">
    <Person>
        <Email>
            vashukevich@mail.ru
        </Email>
        <Nickname>
            vashuk84
        </Nickname>
        <Password>
            01011984
        </Password>
        <Ads>
            <Ad>
                <Description>
                    Хорошая квартира
                </Description>
                <Address>
                    Хоружей 13-12
                </Address>
                <Floor>
                    3
                </Floor>
                <Floors>
                    5
                </Floors>
                <Area>
                    49.0
                </Area>
            </Ad>

            <Ad>
                <Description>
                    Очень хорошая квартира
                </Description>
                <Address>
                    Хоружей 13-12
                </Address>
                <Floor>
                    23
                </Floor>
                <Floors>
                    25
                </Floors>
                <Area>
                    79.0
                </Area>
            </Ad>

        </Ads>
    </Person>
</Persons>
