<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Hotel [
        <!ELEMENT Hotel (Clients, Apartments, Orders)>
        <!ATTLIST Hotel name CDATA #REQUIRED>

        <!ELEMENT Clients (client*)>
        <!ELEMENT client (name, surname, middleName, email, passport, login, password)>
        <!ATTLIST client client_id CDATA #REQUIRED>
        <!ELEMENT login (#PCDATA)>
        <!ELEMENT passport (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT surname (#PCDATA)>
        <!ELEMENT middleName (#PCDATA)>
        <!ELEMENT password (#PCDATA)>
        <!ELEMENT email (#PCDATA)>

        <!ELEMENT Apartments (apartment*)>
        <!ELEMENT apartment (floor, room_number, places, category, cost, status)>
        <!ATTLIST apartment apartment_id CDATA #REQUIRED>
        <!ELEMENT floor (#PCDATA)>
        <!ELEMENT room_number (#PCDATA)>
        <!ELEMENT places (#PCDATA)>
        <!ELEMENT category (#PCDATA)>
        <!ELEMENT cost (#PCDATA)>
        <!ELEMENT status (#PCDATA)>

        <!ELEMENT Orders (order*)>
        <!ELEMENT order (client_id, apartment_id, arrive_date, return_date, bill)>
        <!ATTLIST order order_id CDATA #REQUIRED>
        <!ELEMENT client_id (#PCDATA)>
        <!ELEMENT apartment_id (#PCDATA)>
        <!ELEMENT arrive_date (#PCDATA)>
        <!ELEMENT return_date (#PCDATA)>
        <!ELEMENT bill (#PCDATA)>
        ]>
<Hotel name="Minsk Hotel">
    <Clients>
        <client client_id="1">
            <name>
                Сергей
            </name>
            <surname>
                Рыбкин
            </surname>
            <middleName>
                Владимирович
            </middleName>
            <email>
                serp@gmail.com
            </email>
            <passport>
                KH3125325
            </passport>
            <login>
                serg
            </login>
            <password>
                123qwe
            </password>
        </client>
        <client client_id="2">
            <name>
                Павел
            </name>
            <surname>
                Свободин
            </surname>
            <middleName>
                Владимирович
            </middleName>
            <email>
                pavel@mail.ru
            </email>
            <passport>
                KH1225253
            </passport>
            <login>
                pashka
            </login>
            <password>
                1qa2ws3ed
            </password>
        </client>
    </Clients>
    <Apartments>
        <apartment apartment_id="1">
            <floor>
                12
            </floor>
            <room_number>
                65
            </room_number>
            <places>
                2
            </places>
            <category>
                basic
            </category>
            <cost>
                45
            </cost>
            <status>
                true or false
            </status>
        </apartment>
        <apartment apartment_id="2">
            <floor>
                6
            </floor>
            <room_number>
                34
            </room_number>
            <places>
                1
            </places>
            <category>
                luxury
            </category>
            <cost>
                350
            </cost>
            <status>
                true or false
            </status>
        </apartment>
    </Apartments>
    <Orders>
        <order order_id="1">
            <client_id>
                1
            </client_id>
            <apartment_id>
                1
            </apartment_id>
            <arrive_date>
                19.10.2016
            </arrive_date>
            <return_date>
                20.10.2016
            </return_date>
            <bill>
                45
            </bill>
        </order>
        <order order_id="2">
            <client_id>
                2
            </client_id>
            <apartment_id>
                2
            </apartment_id>
            <arrive_date>
                16.10.2016
            </arrive_date>
            <return_date>
                20.10.2016
            </return_date>
            <bill>
                350
            </bill>
        </order>
    </Orders>
</Hotel>