=== KateLaurynovich/JD2016-08-29/src/by/it/artiuschik/jd_02_07/TestingSystem.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT Students (Student+)>
        <!ELEMENT Student (Name, Surname,Course,Tests,Results)>
        <!ATTLIST Student
                id #REQUIRED
                >
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Surname (#PCDATA)>
        <!ELEMENT Course (#PCDATA)>
        <!ELEMENT Tests (Test)+>
        <!ELEMENT Test (question)+>
        <!ATTLIST Test
                subject #REQUIRED
                >
        <!ELEMENT question (#PCDATA)>
        <!ATTLIST question
                complexity #IMPLIED>
        <!ELEMENT Results (result)+>
        <!ELEMENT result (#PCDATA)>
        <!ATTLIST result
                subject (#PCDATA)>

=== KateLaurynovich/JD2016-08-29/src/by/it/artiuschik/jd_02_07/TestingSystem.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Students SYSTEM "TestingSystem.dtd" >
<Students>
<Student id="123">
    <Name>Ivanov</Name>
    <Surname>Ivan</Surname>
    <Course>2</Course>
<Tests>
    <Test subject="Algebra">
        <question complexity="hard">Question №1</question>
        <question complexity="easy">Question №2</question>
        <question complexity="easy">Question№3</question>
    </Test>
    <Test subject="Geometry">
        <question complexity="medium">Question №1</question>
        <question complexity="medium">Question №2</question>
        <question complexity="hard">Question№3</question>
    </Test>
    <Test subject="English">
        <question complexity="easy">Question №1</question>
        <question complexity="medium">Question №2</question>
        <question complexity="hard">Question№3</question>
    </Test>
</Tests>
    <Results>
       <result subject="Algebra" >9</result>
        <result subject="Geometry">8</result>
        <result subject="English">9</result>
    </Results>
    </Student>
    </Students>
