<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Persons [
        <!ELEMENT Persons (Person)+>
        <!ELEMENT Person (Email,Nickname,Password,Ads)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Nickname (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Ads (Ad)+>
        <!ELEMENT Ad (Description,Address,Floor,Floors,Area)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Address (#PCDATA)>
        <!ELEMENT Floor (#PCDATA)>
        <!ELEMENT Floors (#PCDATA)>
        <!ELEMENT Area (#PCDATA)>
        ]>
<Persons>
    <Person>
        <Email>
            vashukevich@mail.ru
        </Email>
        <Nickname>
            vashuk84
        </Nickname>
        <Password>
            01011984
        </Password>
        <Ads>

            <Ad>
                <Description> Хорошая квартира</Description>
                <Address>Хоружей 13-12</Address>
                <Floor>3</Floor>
                <Floors>5</Floors>
                <Area>49.0</Area>
            </Ad>

            <Ad>
                <Description> Очень хорошая квартира</Description>
                <Address>Хоружей 13-12</Address>
                <Floor>23</Floor>
                <Floors>25</Floors>
                <Area>79.0</Area>
            </Ad>
        </Ads>
    </Person>
</Persons>